# Generated by Django 4.1.1 on 2026-03-04 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSchema',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, default='', verbose_name='description')),
                ('schema', models.JSONField(default=dict, verbose_name='schema')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='version')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_form_schemas', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'form schema',
                'verbose_name_plural': 'form schemas',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict, verbose_name='data')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_responses', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='e3_dynamic_forms.formschema', verbose_name='schema')),
            ],
            options={
                'verbose_name': 'form response',
                'verbose_name_plural': 'form responses',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='updated date')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=255, verbose_name='field name')),
                ('file', models.FileField(upload_to='e3_dynamic_forms/attachments/%Y/%m/', verbose_name='file')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_attachments', to='e3_dynamic_forms.formresponse', verbose_name='response')),
            ],
            options={
                'verbose_name': 'attachment',
                'verbose_name_plural': 'attachments',
                'abstract': False,
                'swappable': 'DYNAMIC_FORMS_ATTACHMENT_MODEL',
            },
        ),
    ]
